const prisma = require("../db/prisma");
const { getDailyActivityOverview, getPageTrafficBreakdown } = require("./eventService");

const MS_PER_DAY = 24 * 60 * 60 * 1000;

/**
 * Midnight-to-midnight UTC window for the day before `referenceDate`.
 */
const getPreviousDayRange = (referenceDate = new Date()) => {
    const todayStart = new Date(Date.UTC(
        referenceDate.getUTCFullYear(),
        referenceDate.getUTCMonth(),
        referenceDate.getUTCDate()
    ));
    const startDate = new Date(todayStart.getTime() - MS_PER_DAY);
    const endDate = new Date(todayStart.getTime() - 1);
    return { startDate, endDate };
};

/**
 * Build the previous day's activity report from the user_event (+ user) tables
 */
const buildDailyActivityReport = async (referenceDate = new Date()) => {
    const { startDate, endDate } = getPreviousDayRange(referenceDate);

    const [overview, topPages, newSignups] = await Promise.all([
        getDailyActivityOverview(startDate, endDate),
        getPageTrafficBreakdown(startDate, endDate),
        prisma.user.count({ where: { createdAt: { gte: startDate, lte: endDate } } })
    ]);

    return { startDate, endDate, ...overview, topPages, newSignups };
};

const escapeHtml = (str) => String(str).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
}[c]));

const formatDate = (date) => date.toISOString().slice(0, 10);

/**
 * Format a report built by buildDailyActivityReport() into an email {subject, html, text}
 */
const formatDailyActivityReportEmail = (report) => {
    const { startDate, eventTypeBreakdown, topPages, totalEvents, uniqueVisitors, uniqueLoggedInUsers, newSignups } = report;
    const dateLabel = formatDate(startDate);
    const topTenPages = topPages.slice(0, 10);

    const eventRows = eventTypeBreakdown.length
        ? eventTypeBreakdown.map(e => `<tr><td>${escapeHtml(e.eventType)}</td><td style="text-align:right">${e.count}</td></tr>`).join("")
        : `<tr><td colspan="2">No events recorded</td></tr>`;

    const pageRows = topTenPages.length
        ? topTenPages.map(p => `<tr><td>${escapeHtml(p.page)}</td><td style="text-align:right">${p.pageViews}</td><td style="text-align:right">${p.uniqueVisitors}</td></tr>`).join("")
        : `<tr><td colspan="3">No page views recorded</td></tr>`;

    const html = `
    <div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #1a1a1a;">
      <h2 style="color:#0f766e; margin-bottom:4px;">cricBid — Daily Activity Summary</h2>
      <p style="color:#555; margin-top:0;">Activity for <strong>${dateLabel}</strong></p>

      <table style="width:100%; border-collapse:collapse; margin-bottom:24px;">
        <tr>
          <td style="padding:12px; background:#f0fdfa; border-radius:6px; text-align:center;"><strong style="font-size:18px;">${totalEvents}</strong><br/><span style="font-size:12px; color:#555;">Total events</span></td>
          <td style="padding:12px; background:#f0fdfa; border-radius:6px; text-align:center;"><strong style="font-size:18px;">${uniqueVisitors}</strong><br/><span style="font-size:12px; color:#555;">Unique visitors</span></td>
          <td style="padding:12px; background:#f0fdfa; border-radius:6px; text-align:center;"><strong style="font-size:18px;">${uniqueLoggedInUsers}</strong><br/><span style="font-size:12px; color:#555;">Active logged-in users</span></td>
          <td style="padding:12px; background:#f0fdfa; border-radius:6px; text-align:center;"><strong style="font-size:18px;">${newSignups}</strong><br/><span style="font-size:12px; color:#555;">New signups</span></td>
        </tr>
      </table>

      <h3 style="margin-bottom:8px;">Events by type</h3>
      <table style="width:100%; border-collapse:collapse;" cellpadding="6">
        <thead><tr style="background:#f3f4f6; text-align:left;"><th>Event type</th><th style="text-align:right">Count</th></tr></thead>
        <tbody>${eventRows}</tbody>
      </table>

      <h3 style="margin-bottom:8px; margin-top:24px;">Top pages</h3>
      <table style="width:100%; border-collapse:collapse;" cellpadding="6">
        <thead><tr style="background:#f3f4f6; text-align:left;"><th>Page</th><th style="text-align:right">Views</th><th style="text-align:right">Unique visitors</th></tr></thead>
        <tbody>${pageRows}</tbody>
      </table>

      <p style="color:#999; font-size:12px; margin-top:24px;">Automated daily report generated by cricBid.</p>
    </div>`;

    const text = [
        `cricBid - Daily Activity Summary for ${dateLabel}`,
        "",
        `Total events: ${totalEvents}`,
        `Unique visitors: ${uniqueVisitors}`,
        `Active logged-in users: ${uniqueLoggedInUsers}`,
        `New signups: ${newSignups}`,
        "",
        "Events by type:",
        ...(eventTypeBreakdown.length ? eventTypeBreakdown.map(e => `  ${e.eventType}: ${e.count}`) : ["  No events recorded"]),
        "",
        "Top pages:",
        ...(topTenPages.length ? topTenPages.map(p => `  ${p.page}: ${p.pageViews} views (${p.uniqueVisitors} unique)`) : ["  No page views recorded"])
    ].join("\n");

    return {
        subject: `cricBid Daily Activity Summary - ${dateLabel}`,
        html,
        text
    };
};

module.exports = { getPreviousDayRange, buildDailyActivityReport, formatDailyActivityReportEmail };
