import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import apiConfig from "@/config/apiConfig";

// ── Theme (matches CricBid primary purple + slate) ──────────────────────────
const PURPLE: [number, number, number] = [109, 40, 217];      // #6D28D9
const PURPLE_LIGHT: [number, number, number] = [139, 92, 246]; // #8B5CF6
const PURPLE_DARK: [number, number, number] = [76, 29, 149];   // #4C1D95
const WHITE: [number, number, number] = [255, 255, 255];
const SLATE_900: [number, number, number] = [15, 23, 42];
const SLATE_700: [number, number, number] = [51, 65, 85];
const SLATE_400: [number, number, number] = [148, 163, 184];
const SLATE_200: [number, number, number] = [226, 232, 240];
const SLATE_100: [number, number, number] = [241, 245, 249];
const GREEN: [number, number, number] = [22, 163, 74];         // sold
const AMBER: [number, number, number] = [180, 83, 9];          // unsold

interface ExportPlayer {
  auctionSerialNumber: number | string;
  name: string;
  age: string;
  playerCategory: string;
  skill: string;
  mobile: string;
  teamName: string;
  sold: string;
  amtSold: number;
}

interface ExportTeam {
  name: string;
  ownerName: string;
  ownerMobile: string;
}

function drawPageHeader(doc: jsPDF, tournamentName: string) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...PURPLE_DARK);
  doc.rect(0, 0, w, 10, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PURPLE_LIGHT);
  doc.text("CRICBID", 14, 6.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...SLATE_400);
  doc.text(`${tournamentName} — Auction Report`, w / 2, 6.5, { align: "center" });
  const dateStr = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  doc.text(dateStr, w - 14, 6.5, { align: "right" });
}

function drawPageFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...PURPLE_DARK);
  doc.rect(0, h - 8, w, 8, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...SLATE_400);
  doc.text("Generated by CricBid • cricbid.online", 14, h - 3);
  doc.text(`Page ${pageNum} of ${totalPages}`, w - 14, h - 3, { align: "right" });
}

export async function exportAuctionReport(tournamentName: string, tournamentId: string): Promise<void> {
  if (!tournamentId) throw new Error("No tournament selected");

  const user = (() => {
    try { return JSON.parse(localStorage.getItem("user") || "{}"); } catch { return {}; }
  })();

  const res = await fetch(`${apiConfig.baseUrl}/api/tournament/export`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-user-id": user._id || "" },
    body: JSON.stringify({ tournamentId, userId: user._id }),
  });
  if (!res.ok) throw new Error("Failed to fetch auction data");
  const result = await res.json();
  const data = result.data;

  const allPlayers: ExportPlayer[] = data.players || [];
  const allTeams: ExportTeam[] = data.teams || [];

  const soldPlayers = allPlayers.filter(p => p.sold === "Yes" || p.sold === true || p.amtSold > 0);
  const unsoldPlayers = allPlayers.filter(p => !(p.sold === "Yes" || p.sold === true || p.amtSold > 0));
  const totalRevenue = soldPlayers.reduce((s, p) => s + (p.amtSold || 0), 0);

  // Group players by team
  const playersByTeam = new Map<string, ExportPlayer[]>();
  for (const team of allTeams) {
    playersByTeam.set(team.name, []);
  }
  for (const player of soldPlayers) {
    if (player.teamName) {
      const arr = playersByTeam.get(player.teamName) ?? [];
      arr.push(player);
      playersByTeam.set(player.teamName, arr);
    }
  }

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  // ── COVER PAGE ────────────────────────────────────────────────────────────

  // Full purple header band
  doc.setFillColor(...PURPLE_DARK);
  doc.rect(0, 0, pw, 80, "F");

  // Decorative diagonal stripe
  doc.setFillColor(...PURPLE);
  doc.triangle(0, 60, pw, 40, pw, 80, "F");

  // CRICBID wordmark
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PURPLE_LIGHT);
  doc.text("CRICBID", pw / 2, 22, { align: "center" });

  // Tournament name
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...WHITE);
  const nameLine = tournamentName || "Tournament";
  doc.text(nameLine, pw / 2, 40, { align: "center", maxWidth: pw - 28 });

  // Report type label
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(196, 181, 253); // purple-300
  doc.text("Auction Results Report", pw / 2, 52, { align: "center" });

  // Date pill
  const dateStr = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  doc.setFontSize(9);
  doc.setTextColor(...SLATE_400);
  doc.text(dateStr, pw / 2, 62, { align: "center" });

  // ── Summary stat cards ───────────────────────────────────────────────────
  const cardY = 90;
  const cardH = 26;
  const gap = 5;
  const cardW = (pw - 28 - gap * 2) / 3;

  const stats = [
    { label: "Players Sold", value: soldPlayers.length.toString(), color: GREEN },
    { label: "Total Spent", value: `₹${totalRevenue.toLocaleString("en-IN")}`, color: PURPLE },
    { label: "Unsold Players", value: unsoldPlayers.length.toString(), color: AMBER },
  ];

  stats.forEach(({ label, value, color }, i) => {
    const x = 14 + i * (cardW + gap);
    doc.setFillColor(...SLATE_100);
    doc.roundedRect(x, cardY, cardW, cardH, 3, 3, "F");
    doc.setDrawColor(...SLATE_200);
    doc.setLineWidth(0.4);
    doc.roundedRect(x, cardY, cardW, cardH, 3, 3, "S");

    // Color accent left border
    doc.setFillColor(...color);
    doc.roundedRect(x, cardY, 3, cardH, 1.5, 1.5, "F");

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SLATE_700);
    doc.text(label.toUpperCase(), x + 7, cardY + 8);

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...SLATE_900);
    doc.text(value, x + 7, cardY + 20);
  });

  // ── Teams summary table ──────────────────────────────────────────────────
  const tableStartY = cardY + cardH + 12;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...SLATE_900);
  doc.text("Teams at a Glance", 14, tableStartY);

  const summaryRows = allTeams.map(team => {
    const tp = playersByTeam.get(team.name) || [];
    const spent = tp.reduce((s, p) => s + (p.amtSold || 0), 0);
    return [
      team.name,
      team.ownerName || "—",
      tp.length.toString(),
      `₹${spent.toLocaleString("en-IN")}`,
    ];
  });

  autoTable(doc, {
    startY: tableStartY + 4,
    margin: { left: 14, right: 14 },
    head: [["Team", "Owner", "Players", "Total Spent"]],
    body: summaryRows,
    theme: "grid",
    styles: {
      fontSize: 10,
      cellPadding: 3.5,
      lineColor: SLATE_200,
      lineWidth: 0.3,
      textColor: SLATE_900,
    },
    headStyles: {
      fillColor: PURPLE,
      textColor: WHITE,
      fontStyle: "bold",
      fontSize: 10,
    },
    alternateRowStyles: { fillColor: SLATE_100 },
    columnStyles: {
      0: { fontStyle: "bold" },
      2: { halign: "center" },
      3: { halign: "right" },
    },
  });

  // Cover page footer
  doc.setFillColor(...PURPLE_DARK);
  doc.rect(0, ph - 8, pw, 8, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...SLATE_400);
  doc.text("Generated by CricBid • cricbid.online", pw / 2, ph - 3, { align: "center" });

  // ── PER-TEAM PAGES ────────────────────────────────────────────────────────
  for (const team of allTeams) {
    doc.addPage();

    const players = playersByTeam.get(team.name) || [];
    const teamSpent = players.reduce((s, p) => s + (p.amtSold || 0), 0);

    drawPageHeader(doc, tournamentName);

    // Team banner
    const bannerY = 14;
    doc.setFillColor(...PURPLE);
    doc.roundedRect(14, bannerY, pw - 28, 22, 3, 3, "F");

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text(team.name, 21, bannerY + 9);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(216, 180, 254); // purple-200
    const ownerLabel = team.ownerName ? `Owner: ${team.ownerName}` : "";
    const mobileLabel = team.ownerMobile ? `  •  ${team.ownerMobile}` : "";
    doc.text(ownerLabel + mobileLabel, 21, bannerY + 17);

    // Spent badge on right
    const spentText = `₹${teamSpent.toLocaleString("en-IN")} spent`;
    const badgeW = doc.getTextWidth(spentText) + 10;
    const badgeX = pw - 14 - badgeW;
    doc.setFillColor(255, 255, 255, 0.15);
    doc.roundedRect(badgeX, bannerY + 5, badgeW, 12, 2, 2, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text(spentText, badgeX + 5, bannerY + 13);

    // Players count sub-label
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(216, 180, 254);
    doc.text(`${players.length} player${players.length !== 1 ? "s" : ""} acquired`, badgeX + 5, bannerY + 21);

    if (players.length === 0) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...SLATE_400);
      doc.text("No players acquired by this team", pw / 2, bannerY + 44, { align: "center" });
    } else {
      const tableRows = players.map((p, idx) => [
        (idx + 1).toString(),
        p.name || "—",
        p.playerCategory || "—",
        p.skill || "—",
        p.amtSold > 0 ? `₹${p.amtSold.toLocaleString("en-IN")}` : "—",
      ]);

      autoTable(doc, {
        startY: bannerY + 26,
        margin: { left: 14, right: 14 },
        head: [["#", "Player Name", "Category", "Role / Skill", "Amount"]],
        body: tableRows,
        theme: "grid",
        styles: {
          fontSize: 10,
          cellPadding: 3.5,
          lineColor: SLATE_200,
          lineWidth: 0.3,
          textColor: SLATE_900,
        },
        headStyles: {
          fillColor: PURPLE_DARK,
          textColor: WHITE,
          fontStyle: "bold",
          fontSize: 10,
          halign: "left",
          cellPadding: 4,
        },
        alternateRowStyles: { fillColor: SLATE_100 },
        columnStyles: {
          0: { cellWidth: 12, halign: "center", fontStyle: "bold" },
          1: { fontStyle: "bold" },
          2: { cellWidth: 40, halign: "center" },
          3: { cellWidth: 40, halign: "center" },
          4: { cellWidth: 32, halign: "right", fontStyle: "bold" },
        },
        didParseCell: (data) => {
          // Highlight amount column in purple tint
          if (data.column.index === 4 && data.section === "body") {
            data.cell.styles.textColor = PURPLE;
          }
        },
      });
    }

    drawPageFooter(doc, doc.getNumberOfPages(), doc.getNumberOfPages());
  }

  // ── UNSOLD PAGE (if any) ─────────────────────────────────────────────────
  if (unsoldPlayers.length > 0) {
    doc.addPage();
    drawPageHeader(doc, tournamentName);

    const bannerY = 14;
    doc.setFillColor(...SLATE_700);
    doc.roundedRect(14, bannerY, pw - 28, 16, 3, 3, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text("Unsold Players", 21, bannerY + 10.5);

    const badgeW2 = 32;
    doc.setFillColor(...AMBER);
    doc.roundedRect(pw - 14 - badgeW2, bannerY + 4, badgeW2, 8, 1.5, 1.5, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text(`${unsoldPlayers.length} players`, pw - 14 - badgeW2 + 4, bannerY + 9.5);

    const unsoldRows = unsoldPlayers.map((p, idx) => [
      (idx + 1).toString(),
      p.name || "—",
      p.playerCategory || "—",
      p.skill || "—",
    ]);

    autoTable(doc, {
      startY: bannerY + 20,
      margin: { left: 14, right: 14 },
      head: [["#", "Player Name", "Category", "Role / Skill"]],
      body: unsoldRows,
      theme: "grid",
      styles: {
        fontSize: 10,
        cellPadding: 3.5,
        lineColor: SLATE_200,
        lineWidth: 0.3,
        textColor: SLATE_900,
      },
      headStyles: {
        fillColor: SLATE_700,
        textColor: WHITE,
        fontStyle: "bold",
        fontSize: 10,
      },
      alternateRowStyles: { fillColor: SLATE_100 },
      columnStyles: {
        0: { cellWidth: 12, halign: "center", fontStyle: "bold" },
        1: { fontStyle: "bold" },
        2: { cellWidth: 44, halign: "center" },
        3: { cellWidth: 44, halign: "center" },
      },
    });

    drawPageFooter(doc, doc.getNumberOfPages(), doc.getNumberOfPages());
  }

  // Fix page numbers now that we know total
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i > 1) drawPageFooter(doc, i, totalPages);
  }

  const safeName = (tournamentName || "tournament").replace(/[^a-zA-Z0-9]/g, "_").toLowerCase();
  doc.save(`${safeName}_auction_report.pdf`);
}
